// Code generated by protoc-gen-go. DO NOT EDIT.
// source: audio.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AudioSample struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AudioSample) Reset()         { *m = AudioSample{} }
func (m *AudioSample) String() string { return proto.CompactTextString(m) }
func (*AudioSample) ProtoMessage()    {}
func (*AudioSample) Descriptor() ([]byte, []int) {
	return fileDescriptor_fae679ade197b92f, []int{0}
}

func (m *AudioSample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AudioSample.Unmarshal(m, b)
}
func (m *AudioSample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AudioSample.Marshal(b, m, deterministic)
}
func (m *AudioSample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AudioSample.Merge(m, src)
}
func (m *AudioSample) XXX_Size() int {
	return xxx_messageInfo_AudioSample.Size(m)
}
func (m *AudioSample) XXX_DiscardUnknown() {
	xxx_messageInfo_AudioSample.DiscardUnknown(m)
}

var xxx_messageInfo_AudioSample proto.InternalMessageInfo

func (m *AudioSample) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*AudioSample)(nil), "proto.AudioSample")
}

func init() {
	proto.RegisterFile("audio.proto", fileDescriptor_fae679ade197b92f)
}

var fileDescriptor_fae679ade197b92f = []byte{
	// 101 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x2c, 0x4d, 0xc9,
	0xcc, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x8a, 0x5c, 0xdc, 0x8e,
	0x20, 0xd1, 0xe0, 0xc4, 0xdc, 0x82, 0x9c, 0x54, 0x21, 0x21, 0x2e, 0x96, 0x94, 0xc4, 0x92, 0x44,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x30, 0xdb, 0x49, 0x95, 0x8b, 0x2f, 0x39, 0x3f, 0x57,
	0x2f, 0x35, 0x39, 0x03, 0xaa, 0xd7, 0x89, 0x0b, 0xac, 0x25, 0x00, 0xc4, 0x8e, 0x62, 0xd7, 0xb3,
	0x06, 0x0b, 0x26, 0xb1, 0x81, 0x29, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x03, 0x24, 0x4f,
	0x8b, 0x66, 0x00, 0x00, 0x00,
}
