// Code generated by protoc-gen-go. DO NOT EDIT.
// source: context.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Context struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Confidence           string   `protobuf:"bytes,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	SessionId            string   `protobuf:"bytes,3,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Context) Reset()         { *m = Context{} }
func (m *Context) String() string { return proto.CompactTextString(m) }
func (*Context) ProtoMessage()    {}
func (*Context) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64063be2fc89884, []int{0}
}

func (m *Context) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context.Unmarshal(m, b)
}
func (m *Context) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context.Marshal(b, m, deterministic)
}
func (m *Context) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context.Merge(m, src)
}
func (m *Context) XXX_Size() int {
	return xxx_messageInfo_Context.Size(m)
}
func (m *Context) XXX_DiscardUnknown() {
	xxx_messageInfo_Context.DiscardUnknown(m)
}

var xxx_messageInfo_Context proto.InternalMessageInfo

func (m *Context) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *Context) GetConfidence() string {
	if m != nil {
		return m.Confidence
	}
	return ""
}

func (m *Context) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func init() {
	proto.RegisterType((*Context)(nil), "proto.Context")
}

func init() {
	proto.RegisterFile("context.proto", fileDescriptor_b64063be2fc89884)
}

var fileDescriptor_b64063be2fc89884 = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0xcf, 0x2b,
	0x49, 0xad, 0x28, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xc9, 0x5c,
	0xec, 0xce, 0x10, 0x71, 0x21, 0x29, 0x2e, 0x8e, 0xcc, 0x94, 0xd4, 0xbc, 0x92, 0xcc, 0x92, 0x4a,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x38, 0x5f, 0x48, 0x8e, 0x8b, 0x2b, 0x39, 0x3f, 0x2f,
	0x0d, 0xc4, 0x4f, 0x4e, 0x95, 0x60, 0x02, 0xcb, 0x22, 0x89, 0x08, 0xc9, 0x70, 0x71, 0x16, 0xa7,
	0x16, 0x17, 0x67, 0xe6, 0xe7, 0x79, 0xa6, 0x48, 0x30, 0x83, 0xa5, 0x11, 0x02, 0x4e, 0xea, 0x5c,
	0x7c, 0xc9, 0xf9, 0xb9, 0x7a, 0xa9, 0xc9, 0x19, 0xf9, 0x10, 0xdb, 0x9d, 0x78, 0xa0, 0x96, 0x06,
	0x80, 0x78, 0x51, 0xec, 0x7a, 0xd6, 0x60, 0xe1, 0x24, 0x36, 0x30, 0x65, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0x2b, 0x9f, 0x9f, 0x48, 0xac, 0x00, 0x00, 0x00,
}
