// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dialog.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Detect struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Audio                []byte   `protobuf:"bytes,2,opt,name=audio,proto3" json:"audio,omitempty"`
	Identity             string   `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	Source               string   `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Detect) Reset()         { *m = Detect{} }
func (m *Detect) String() string { return proto.CompactTextString(m) }
func (*Detect) ProtoMessage()    {}
func (*Detect) Descriptor() ([]byte, []int) {
	return fileDescriptor_68a9e8739acd3625, []int{0}
}

func (m *Detect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Detect.Unmarshal(m, b)
}
func (m *Detect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Detect.Marshal(b, m, deterministic)
}
func (m *Detect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Detect.Merge(m, src)
}
func (m *Detect) XXX_Size() int {
	return xxx_messageInfo_Detect.Size(m)
}
func (m *Detect) XXX_DiscardUnknown() {
	xxx_messageInfo_Detect.DiscardUnknown(m)
}

var xxx_messageInfo_Detect proto.InternalMessageInfo

func (m *Detect) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Detect) GetAudio() []byte {
	if m != nil {
		return m.Audio
	}
	return nil
}

func (m *Detect) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *Detect) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type Intent struct {
	Vendor                   string           `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Skill                    string           `protobuf:"bytes,2,opt,name=skill,proto3" json:"skill,omitempty"`
	Command                  string           `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Query                    string           `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	Text                     string           `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	Confidence               float32          `protobuf:"fixed32,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	AllRequiredParamsPresent bool             `protobuf:"varint,7,opt,name=all_required_params_present,json=allRequiredParamsPresent,proto3" json:"all_required_params_present,omitempty"`
	Parameters               *_struct.Struct  `protobuf:"bytes,8,opt,name=parameters,proto3" json:"parameters,omitempty"`
	OutputContexts           []*OutputContext `protobuf:"bytes,9,rep,name=output_contexts,json=outputContexts,proto3" json:"output_contexts,omitempty"`
	Context                  *Context         `protobuf:"bytes,10,opt,name=context,proto3" json:"context,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}         `json:"-"`
	XXX_unrecognized         []byte           `json:"-"`
	XXX_sizecache            int32            `json:"-"`
}

func (m *Intent) Reset()         { *m = Intent{} }
func (m *Intent) String() string { return proto.CompactTextString(m) }
func (*Intent) ProtoMessage()    {}
func (*Intent) Descriptor() ([]byte, []int) {
	return fileDescriptor_68a9e8739acd3625, []int{1}
}

func (m *Intent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Intent.Unmarshal(m, b)
}
func (m *Intent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Intent.Marshal(b, m, deterministic)
}
func (m *Intent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Intent.Merge(m, src)
}
func (m *Intent) XXX_Size() int {
	return xxx_messageInfo_Intent.Size(m)
}
func (m *Intent) XXX_DiscardUnknown() {
	xxx_messageInfo_Intent.DiscardUnknown(m)
}

var xxx_messageInfo_Intent proto.InternalMessageInfo

func (m *Intent) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *Intent) GetSkill() string {
	if m != nil {
		return m.Skill
	}
	return ""
}

func (m *Intent) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *Intent) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *Intent) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Intent) GetConfidence() float32 {
	if m != nil {
		return m.Confidence
	}
	return 0
}

func (m *Intent) GetAllRequiredParamsPresent() bool {
	if m != nil {
		return m.AllRequiredParamsPresent
	}
	return false
}

func (m *Intent) GetParameters() *_struct.Struct {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *Intent) GetOutputContexts() []*OutputContext {
	if m != nil {
		return m.OutputContexts
	}
	return nil
}

func (m *Intent) GetContext() *Context {
	if m != nil {
		return m.Context
	}
	return nil
}

type OutputContext struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Lifespan             int32    `protobuf:"varint,2,opt,name=lifespan,proto3" json:"lifespan,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutputContext) Reset()         { *m = OutputContext{} }
func (m *OutputContext) String() string { return proto.CompactTextString(m) }
func (*OutputContext) ProtoMessage()    {}
func (*OutputContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_68a9e8739acd3625, []int{2}
}

func (m *OutputContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutputContext.Unmarshal(m, b)
}
func (m *OutputContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutputContext.Marshal(b, m, deterministic)
}
func (m *OutputContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutputContext.Merge(m, src)
}
func (m *OutputContext) XXX_Size() int {
	return xxx_messageInfo_OutputContext.Size(m)
}
func (m *OutputContext) XXX_DiscardUnknown() {
	xxx_messageInfo_OutputContext.DiscardUnknown(m)
}

var xxx_messageInfo_OutputContext proto.InternalMessageInfo

func (m *OutputContext) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OutputContext) GetLifespan() int32 {
	if m != nil {
		return m.Lifespan
	}
	return 0
}

type Context struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Confidence           string   `protobuf:"bytes,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Context) Reset()         { *m = Context{} }
func (m *Context) String() string { return proto.CompactTextString(m) }
func (*Context) ProtoMessage()    {}
func (*Context) Descriptor() ([]byte, []int) {
	return fileDescriptor_68a9e8739acd3625, []int{3}
}

func (m *Context) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context.Unmarshal(m, b)
}
func (m *Context) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context.Marshal(b, m, deterministic)
}
func (m *Context) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context.Merge(m, src)
}
func (m *Context) XXX_Size() int {
	return xxx_messageInfo_Context.Size(m)
}
func (m *Context) XXX_DiscardUnknown() {
	xxx_messageInfo_Context.DiscardUnknown(m)
}

var xxx_messageInfo_Context proto.InternalMessageInfo

func (m *Context) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *Context) GetConfidence() string {
	if m != nil {
		return m.Confidence
	}
	return ""
}

func init() {
	proto.RegisterType((*Detect)(nil), "proto.Detect")
	proto.RegisterType((*Intent)(nil), "proto.Intent")
	proto.RegisterType((*OutputContext)(nil), "proto.OutputContext")
	proto.RegisterType((*Context)(nil), "proto.Context")
}

func init() {
	proto.RegisterFile("dialog.proto", fileDescriptor_68a9e8739acd3625)
}

var fileDescriptor_68a9e8739acd3625 = []byte{
	// 437 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x52, 0xcf, 0x8b, 0x13, 0x31,
	0x14, 0x66, 0xba, 0xdb, 0x69, 0xfb, 0xda, 0x5d, 0x21, 0x2c, 0x1a, 0xaa, 0xc8, 0x50, 0x3c, 0xcc,
	0x41, 0x66, 0xa1, 0x82, 0x1e, 0x64, 0x11, 0xd6, 0xf5, 0xe0, 0xc9, 0x12, 0x6f, 0x5e, 0x4a, 0xcc,
	0xbc, 0xd6, 0x61, 0x33, 0xc9, 0x6c, 0x92, 0x11, 0xf7, 0x6f, 0xf7, 0x22, 0xf9, 0x31, 0x65, 0xd6,
	0x53, 0xf2, 0xe5, 0x7d, 0x2f, 0x5f, 0xf2, 0x7d, 0x0f, 0x56, 0x75, 0xc3, 0xa5, 0x3e, 0x56, 0x9d,
	0xd1, 0x4e, 0x93, 0x69, 0x58, 0xd6, 0xaf, 0x8e, 0x5a, 0x1f, 0x25, 0x5e, 0x07, 0xf4, 0xb3, 0x3f,
	0x5c, 0x5b, 0x67, 0x7a, 0xe1, 0x22, 0x69, 0x73, 0x80, 0xfc, 0x0e, 0x1d, 0x0a, 0x47, 0x08, 0x9c,
	0x3b, 0xfc, 0xe3, 0x68, 0x56, 0x64, 0xe5, 0x82, 0x85, 0x3d, 0xb9, 0x82, 0x29, 0xef, 0xeb, 0x46,
	0xd3, 0x49, 0x91, 0x95, 0x2b, 0x16, 0x01, 0x59, 0xc3, 0xbc, 0xa9, 0x51, 0xb9, 0xc6, 0x3d, 0xd2,
	0xb3, 0xc0, 0x3e, 0x61, 0xf2, 0x1c, 0x72, 0xab, 0x7b, 0x23, 0x90, 0x9e, 0x87, 0x4a, 0x42, 0x9b,
	0xbf, 0x13, 0xc8, 0xbf, 0x2a, 0x87, 0xca, 0x79, 0xca, 0x6f, 0x54, 0xb5, 0x36, 0x49, 0x2a, 0x21,
	0x2f, 0x66, 0xef, 0x1b, 0x29, 0x83, 0xd8, 0x82, 0x45, 0x40, 0x28, 0xcc, 0x84, 0x6e, 0x5b, 0xae,
	0xea, 0xa4, 0x35, 0x40, 0xcf, 0x7f, 0xe8, 0xd1, 0x3c, 0x26, 0xa5, 0x08, 0x4e, 0xdf, 0x98, 0x8e,
	0xbe, 0xf1, 0x1a, 0x40, 0x68, 0x75, 0xf0, 0x8f, 0x14, 0x48, 0xf3, 0x22, 0x2b, 0x27, 0x6c, 0x74,
	0x42, 0x6e, 0xe0, 0x25, 0x97, 0x72, 0x6f, 0xf0, 0xa1, 0x6f, 0x0c, 0xd6, 0xfb, 0x8e, 0x1b, 0xde,
	0xda, 0x7d, 0x67, 0xd0, 0xa2, 0x72, 0x74, 0x56, 0x64, 0xe5, 0x9c, 0x51, 0x2e, 0x25, 0x4b, 0x8c,
	0x5d, 0x20, 0xec, 0x62, 0x9d, 0x7c, 0x00, 0x08, 0x1d, 0xe8, 0xd0, 0x58, 0x3a, 0x2f, 0xb2, 0x72,
	0xb9, 0x7d, 0x51, 0x45, 0xdb, 0xab, 0xc1, 0xf6, 0xea, 0x7b, 0xb0, 0x9d, 0x8d, 0xa8, 0xe4, 0x06,
	0x9e, 0xe9, 0xde, 0x75, 0xbd, 0xdb, 0x0b, 0xad, 0xfc, 0x4b, 0x2d, 0x5d, 0x14, 0x67, 0xe5, 0x72,
	0x7b, 0x15, 0xdb, 0xaa, 0x6f, 0xa1, 0xfa, 0x39, 0x16, 0xd9, 0xa5, 0x1e, 0x43, 0x4b, 0x4a, 0x6f,
	0x4d, 0xd8, 0x53, 0x08, 0xa2, 0x97, 0xa9, 0x6d, 0x68, 0x18, 0xca, 0x9b, 0x4f, 0x70, 0xf1, 0xe4,
	0x2a, 0xef, 0x92, 0xe2, 0x2d, 0x0e, 0x61, 0xfb, 0xbd, 0x8f, 0x55, 0x36, 0x07, 0xb4, 0x1d, 0x57,
	0x21, 0x82, 0x29, 0x3b, 0xe1, 0xcd, 0x17, 0x98, 0x0d, 0xad, 0xe3, 0xf4, 0xb3, 0xff, 0xd2, 0x7f,
	0x6a, 0x74, 0xcc, 0x6b, 0x74, 0xb2, 0x7d, 0x0f, 0xf9, 0x5d, 0x18, 0x51, 0xf2, 0x16, 0x56, 0x71,
	0xee, 0xd2, 0x50, 0x5c, 0xa4, 0xa7, 0xc7, 0xc3, 0xf5, 0x00, 0x63, 0xf5, 0xf6, 0x0d, 0xac, 0x84,
	0x6e, 0x2b, 0x14, 0xbf, 0x74, 0x65, 0xeb, 0xfb, 0xdb, 0x65, 0xbc, 0x65, 0xe7, 0x39, 0x3f, 0x66,
	0xd5, 0xc7, 0x68, 0x72, 0x1e, 0x96, 0x77, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x7e, 0xf8, 0x1a,
	0xb9, 0x07, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DialogClient is the client API for Dialog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DialogClient interface {
	DetectIntent(ctx context.Context, in *Detect, opts ...grpc.CallOption) (*Intent, error)
}

type dialogClient struct {
	cc grpc.ClientConnInterface
}

func NewDialogClient(cc grpc.ClientConnInterface) DialogClient {
	return &dialogClient{cc}
}

func (c *dialogClient) DetectIntent(ctx context.Context, in *Detect, opts ...grpc.CallOption) (*Intent, error) {
	out := new(Intent)
	err := c.cc.Invoke(ctx, "/proto.Dialog/DetectIntent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DialogServer is the server API for Dialog service.
type DialogServer interface {
	DetectIntent(context.Context, *Detect) (*Intent, error)
}

// UnimplementedDialogServer can be embedded to have forward compatible implementations.
type UnimplementedDialogServer struct {
}

func (*UnimplementedDialogServer) DetectIntent(ctx context.Context, req *Detect) (*Intent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetectIntent not implemented")
}

func RegisterDialogServer(s *grpc.Server, srv DialogServer) {
	s.RegisterService(&_Dialog_serviceDesc, srv)
}

func _Dialog_DetectIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Detect)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DialogServer).DetectIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dialog/DetectIntent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DialogServer).DetectIntent(ctx, req.(*Detect))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dialog_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Dialog",
	HandlerType: (*DialogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DetectIntent",
			Handler:    _Dialog_DetectIntent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dialog.proto",
}
