// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dialog.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Detect struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Identity             string   `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	Source               string   `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Detect) Reset()         { *m = Detect{} }
func (m *Detect) String() string { return proto.CompactTextString(m) }
func (*Detect) ProtoMessage()    {}
func (*Detect) Descriptor() ([]byte, []int) {
	return fileDescriptor_68a9e8739acd3625, []int{0}
}

func (m *Detect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Detect.Unmarshal(m, b)
}
func (m *Detect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Detect.Marshal(b, m, deterministic)
}
func (m *Detect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Detect.Merge(m, src)
}
func (m *Detect) XXX_Size() int {
	return xxx_messageInfo_Detect.Size(m)
}
func (m *Detect) XXX_DiscardUnknown() {
	xxx_messageInfo_Detect.DiscardUnknown(m)
}

var xxx_messageInfo_Detect proto.InternalMessageInfo

func (m *Detect) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Detect) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *Detect) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type Intent struct {
	Vendor                   string           `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Skill                    string           `protobuf:"bytes,2,opt,name=skill,proto3" json:"skill,omitempty"`
	Command                  string           `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Query                    string           `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	Text                     string           `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	Confidence               float32          `protobuf:"fixed32,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	AllRequiredParamsPresent bool             `protobuf:"varint,7,opt,name=all_required_params_present,json=allRequiredParamsPresent,proto3" json:"all_required_params_present,omitempty"`
	Parameters               *_struct.Struct  `protobuf:"bytes,8,opt,name=parameters,proto3" json:"parameters,omitempty"`
	OutputContexts           []*OutputContext `protobuf:"bytes,9,rep,name=output_contexts,json=outputContexts,proto3" json:"output_contexts,omitempty"`
	Context                  *Context         `protobuf:"bytes,10,opt,name=context,proto3" json:"context,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}         `json:"-"`
	XXX_unrecognized         []byte           `json:"-"`
	XXX_sizecache            int32            `json:"-"`
}

func (m *Intent) Reset()         { *m = Intent{} }
func (m *Intent) String() string { return proto.CompactTextString(m) }
func (*Intent) ProtoMessage()    {}
func (*Intent) Descriptor() ([]byte, []int) {
	return fileDescriptor_68a9e8739acd3625, []int{1}
}

func (m *Intent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Intent.Unmarshal(m, b)
}
func (m *Intent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Intent.Marshal(b, m, deterministic)
}
func (m *Intent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Intent.Merge(m, src)
}
func (m *Intent) XXX_Size() int {
	return xxx_messageInfo_Intent.Size(m)
}
func (m *Intent) XXX_DiscardUnknown() {
	xxx_messageInfo_Intent.DiscardUnknown(m)
}

var xxx_messageInfo_Intent proto.InternalMessageInfo

func (m *Intent) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *Intent) GetSkill() string {
	if m != nil {
		return m.Skill
	}
	return ""
}

func (m *Intent) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *Intent) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *Intent) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Intent) GetConfidence() float32 {
	if m != nil {
		return m.Confidence
	}
	return 0
}

func (m *Intent) GetAllRequiredParamsPresent() bool {
	if m != nil {
		return m.AllRequiredParamsPresent
	}
	return false
}

func (m *Intent) GetParameters() *_struct.Struct {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *Intent) GetOutputContexts() []*OutputContext {
	if m != nil {
		return m.OutputContexts
	}
	return nil
}

func (m *Intent) GetContext() *Context {
	if m != nil {
		return m.Context
	}
	return nil
}

type OutputContext struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Lifespan             int32    `protobuf:"varint,2,opt,name=lifespan,proto3" json:"lifespan,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutputContext) Reset()         { *m = OutputContext{} }
func (m *OutputContext) String() string { return proto.CompactTextString(m) }
func (*OutputContext) ProtoMessage()    {}
func (*OutputContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_68a9e8739acd3625, []int{2}
}

func (m *OutputContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutputContext.Unmarshal(m, b)
}
func (m *OutputContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutputContext.Marshal(b, m, deterministic)
}
func (m *OutputContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutputContext.Merge(m, src)
}
func (m *OutputContext) XXX_Size() int {
	return xxx_messageInfo_OutputContext.Size(m)
}
func (m *OutputContext) XXX_DiscardUnknown() {
	xxx_messageInfo_OutputContext.DiscardUnknown(m)
}

var xxx_messageInfo_OutputContext proto.InternalMessageInfo

func (m *OutputContext) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OutputContext) GetLifespan() int32 {
	if m != nil {
		return m.Lifespan
	}
	return 0
}

type Context struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Confidence           string   `protobuf:"bytes,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	SessionId            string   `protobuf:"bytes,3,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Context) Reset()         { *m = Context{} }
func (m *Context) String() string { return proto.CompactTextString(m) }
func (*Context) ProtoMessage()    {}
func (*Context) Descriptor() ([]byte, []int) {
	return fileDescriptor_68a9e8739acd3625, []int{3}
}

func (m *Context) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context.Unmarshal(m, b)
}
func (m *Context) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context.Marshal(b, m, deterministic)
}
func (m *Context) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context.Merge(m, src)
}
func (m *Context) XXX_Size() int {
	return xxx_messageInfo_Context.Size(m)
}
func (m *Context) XXX_DiscardUnknown() {
	xxx_messageInfo_Context.DiscardUnknown(m)
}

var xxx_messageInfo_Context proto.InternalMessageInfo

func (m *Context) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *Context) GetConfidence() string {
	if m != nil {
		return m.Confidence
	}
	return ""
}

func (m *Context) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func init() {
	proto.RegisterType((*Detect)(nil), "proto.Detect")
	proto.RegisterType((*Intent)(nil), "proto.Intent")
	proto.RegisterType((*OutputContext)(nil), "proto.OutputContext")
	proto.RegisterType((*Context)(nil), "proto.Context")
}

func init() {
	proto.RegisterFile("dialog.proto", fileDescriptor_68a9e8739acd3625)
}

var fileDescriptor_68a9e8739acd3625 = []byte{
	// 470 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x53, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0x56, 0xb6, 0x35, 0x6d, 0x5f, 0x59, 0x41, 0xd6, 0xc4, 0xac, 0x32, 0xa1, 0xa8, 0x07, 0x94,
	0x53, 0x86, 0xca, 0x81, 0x03, 0x1a, 0x88, 0xb1, 0xcb, 0x4e, 0x54, 0x29, 0x27, 0x2e, 0x95, 0x71,
	0x5e, 0x4b, 0x84, 0x63, 0x67, 0xb6, 0x83, 0x36, 0xfe, 0x75, 0x2e, 0xc8, 0x3f, 0x52, 0xb2, 0x9d,
	0xec, 0xcf, 0xdf, 0xf7, 0x5e, 0x5f, 0xbf, 0xef, 0x05, 0x9e, 0x55, 0x35, 0x13, 0x6a, 0x5f, 0xb4,
	0x5a, 0x59, 0x45, 0x46, 0xfe, 0x58, 0x5c, 0xec, 0x95, 0xda, 0x0b, 0xbc, 0xf4, 0xe8, 0x47, 0xb7,
	0xbb, 0x34, 0x56, 0x77, 0xdc, 0x06, 0xd1, 0x62, 0xc6, 0xba, 0xaa, 0x56, 0x01, 0x2c, 0xd7, 0x90,
	0xde, 0xa0, 0x45, 0x6e, 0x09, 0x81, 0x13, 0x8b, 0xf7, 0x96, 0x26, 0x59, 0x92, 0x4f, 0x4b, 0x7f,
	0x27, 0x0b, 0x98, 0xd4, 0x15, 0x4a, 0x5b, 0xdb, 0x07, 0x7a, 0xe4, 0xdf, 0x0f, 0x98, 0xbc, 0x84,
	0xd4, 0xa8, 0x4e, 0x73, 0xa4, 0xc7, 0x9e, 0x89, 0x68, 0xf9, 0xf7, 0x08, 0xd2, 0x5b, 0x69, 0x51,
	0x5a, 0x27, 0xf9, 0x8d, 0xb2, 0x52, 0x3a, 0x36, 0x8d, 0x88, 0x9c, 0xc1, 0xc8, 0xfc, 0xaa, 0x85,
	0x88, 0x3d, 0x03, 0x20, 0x14, 0xc6, 0x5c, 0x35, 0x0d, 0x93, 0x55, 0xec, 0xd8, 0x43, 0xa7, 0xbf,
	0xeb, 0x50, 0x3f, 0xd0, 0x93, 0xa0, 0xf7, 0xe0, 0x30, 0xf0, 0x68, 0x30, 0xf0, 0x6b, 0x00, 0xae,
	0xe4, 0xce, 0x0d, 0xc9, 0x91, 0xa6, 0x59, 0x92, 0x1f, 0x95, 0x83, 0x17, 0x72, 0x05, 0xaf, 0x98,
	0x10, 0x5b, 0x8d, 0x77, 0x5d, 0xad, 0xb1, 0xda, 0xb6, 0x4c, 0xb3, 0xc6, 0x6c, 0x5b, 0x8d, 0x06,
	0xa5, 0xa5, 0xe3, 0x2c, 0xc9, 0x27, 0x25, 0x65, 0x42, 0x94, 0x51, 0xb1, 0xf6, 0x82, 0x75, 0xe0,
	0xc9, 0x7b, 0x00, 0x5f, 0x81, 0x16, 0xb5, 0xa1, 0x93, 0x2c, 0xc9, 0x67, 0xab, 0xf3, 0x22, 0xb8,
	0x5d, 0xf4, 0x6e, 0x17, 0x1b, 0xef, 0x76, 0x39, 0x90, 0x92, 0x2b, 0x78, 0xae, 0x3a, 0xdb, 0x76,
	0x76, 0xcb, 0x95, 0x74, 0x93, 0x1a, 0x3a, 0xcd, 0x8e, 0xf3, 0xd9, 0xea, 0x2c, 0x94, 0x15, 0x5f,
	0x3d, 0xfb, 0x25, 0x90, 0xe5, 0x5c, 0x0d, 0xa1, 0x21, 0xb9, 0xb3, 0xc6, 0xdf, 0x29, 0xf8, 0x1f,
	0x9d, 0xc7, 0xb2, 0xbe, 0xa0, 0xa7, 0x97, 0x9f, 0xe0, 0xf4, 0x51, 0x2b, 0xe7, 0x92, 0x64, 0x0d,
	0xf6, 0xb1, 0xba, 0xbb, 0x8b, 0x55, 0xd4, 0x3b, 0x34, 0x2d, 0x93, 0x3e, 0x82, 0x51, 0x79, 0xc0,
	0x4b, 0x0e, 0xe3, 0xbe, 0x74, 0x98, 0x7e, 0xf2, 0x24, 0xfd, 0xc7, 0x46, 0x87, 0x1c, 0x87, 0x46,
	0x5f, 0xc0, 0xd4, 0xa0, 0x31, 0xb5, 0x92, 0xb7, 0x7d, 0x9c, 0xff, 0x1f, 0x56, 0x7f, 0x20, 0xbd,
	0xf1, 0x7b, 0x4b, 0xde, 0xc2, 0x8b, 0xb0, 0x7f, 0xdf, 0xf0, 0xde, 0xc6, 0xb5, 0x39, 0x8d, 0x7f,
	0x2e, 0x10, 0x8b, 0x1e, 0x46, 0xf6, 0x23, 0x9c, 0x07, 0xe2, 0xb3, 0x5b, 0xe3, 0xf0, 0xb8, 0xb1,
	0x1a, 0x59, 0x43, 0x48, 0x54, 0x7a, 0x66, 0xc3, 0x9a, 0x56, 0xe0, 0x93, 0xea, 0x3c, 0xb9, 0x7e,
	0x03, 0x73, 0xae, 0x9a, 0x02, 0xf9, 0xcf, 0xf8, 0x0d, 0x5c, 0xcf, 0xc2, 0x2c, 0x6b, 0x07, 0xbe,
	0x8f, 0x8b, 0x0f, 0x21, 0xc8, 0xd4, 0x1f, 0xef, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0xd6, 0xe9,
	0x6a, 0x3b, 0x62, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DialogClient is the client API for Dialog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DialogClient interface {
	DetectTextIntent(ctx context.Context, in *Detect, opts ...grpc.CallOption) (*Intent, error)
	DetectAudioIntentStream(ctx context.Context, opts ...grpc.CallOption) (Dialog_DetectAudioIntentStreamClient, error)
}

type dialogClient struct {
	cc grpc.ClientConnInterface
}

func NewDialogClient(cc grpc.ClientConnInterface) DialogClient {
	return &dialogClient{cc}
}

func (c *dialogClient) DetectTextIntent(ctx context.Context, in *Detect, opts ...grpc.CallOption) (*Intent, error) {
	out := new(Intent)
	err := c.cc.Invoke(ctx, "/proto.Dialog/DetectTextIntent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dialogClient) DetectAudioIntentStream(ctx context.Context, opts ...grpc.CallOption) (Dialog_DetectAudioIntentStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Dialog_serviceDesc.Streams[0], "/proto.Dialog/DetectAudioIntentStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &dialogDetectAudioIntentStreamClient{stream}
	return x, nil
}

type Dialog_DetectAudioIntentStreamClient interface {
	Send(*AudioSample) error
	CloseAndRecv() (*Intent, error)
	grpc.ClientStream
}

type dialogDetectAudioIntentStreamClient struct {
	grpc.ClientStream
}

func (x *dialogDetectAudioIntentStreamClient) Send(m *AudioSample) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dialogDetectAudioIntentStreamClient) CloseAndRecv() (*Intent, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Intent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DialogServer is the server API for Dialog service.
type DialogServer interface {
	DetectTextIntent(context.Context, *Detect) (*Intent, error)
	DetectAudioIntentStream(Dialog_DetectAudioIntentStreamServer) error
}

// UnimplementedDialogServer can be embedded to have forward compatible implementations.
type UnimplementedDialogServer struct {
}

func (*UnimplementedDialogServer) DetectTextIntent(ctx context.Context, req *Detect) (*Intent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetectTextIntent not implemented")
}
func (*UnimplementedDialogServer) DetectAudioIntentStream(srv Dialog_DetectAudioIntentStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method DetectAudioIntentStream not implemented")
}

func RegisterDialogServer(s *grpc.Server, srv DialogServer) {
	s.RegisterService(&_Dialog_serviceDesc, srv)
}

func _Dialog_DetectTextIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Detect)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DialogServer).DetectTextIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dialog/DetectTextIntent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DialogServer).DetectTextIntent(ctx, req.(*Detect))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dialog_DetectAudioIntentStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DialogServer).DetectAudioIntentStream(&dialogDetectAudioIntentStreamServer{stream})
}

type Dialog_DetectAudioIntentStreamServer interface {
	SendAndClose(*Intent) error
	Recv() (*AudioSample, error)
	grpc.ServerStream
}

type dialogDetectAudioIntentStreamServer struct {
	grpc.ServerStream
}

func (x *dialogDetectAudioIntentStreamServer) SendAndClose(m *Intent) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dialogDetectAudioIntentStreamServer) Recv() (*AudioSample, error) {
	m := new(AudioSample)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Dialog_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Dialog",
	HandlerType: (*DialogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DetectTextIntent",
			Handler:    _Dialog_DetectTextIntent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DetectAudioIntentStream",
			Handler:       _Dialog_DetectAudioIntentStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "dialog.proto",
}
