// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// DialogClient is the client API for Dialog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DialogClient interface {
	DetectTextIntent(ctx context.Context, in *Detect, opts ...grpc.CallOption) (*Intent, error)
	DetectAudioIntent(ctx context.Context, in *AudioSample, opts ...grpc.CallOption) (*Intent, error)
}

type dialogClient struct {
	cc grpc.ClientConnInterface
}

func NewDialogClient(cc grpc.ClientConnInterface) DialogClient {
	return &dialogClient{cc}
}

func (c *dialogClient) DetectTextIntent(ctx context.Context, in *Detect, opts ...grpc.CallOption) (*Intent, error) {
	out := new(Intent)
	err := c.cc.Invoke(ctx, "/proto.Dialog/DetectTextIntent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dialogClient) DetectAudioIntent(ctx context.Context, in *AudioSample, opts ...grpc.CallOption) (*Intent, error) {
	out := new(Intent)
	err := c.cc.Invoke(ctx, "/proto.Dialog/DetectAudioIntent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DialogServer is the server API for Dialog service.
// All implementations must embed UnimplementedDialogServer
// for forward compatibility
type DialogServer interface {
	DetectTextIntent(context.Context, *Detect) (*Intent, error)
	DetectAudioIntent(context.Context, *AudioSample) (*Intent, error)
	mustEmbedUnimplementedDialogServer()
}

// UnimplementedDialogServer must be embedded to have forward compatible implementations.
type UnimplementedDialogServer struct {
}

func (UnimplementedDialogServer) DetectTextIntent(context.Context, *Detect) (*Intent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetectTextIntent not implemented")
}
func (UnimplementedDialogServer) DetectAudioIntent(context.Context, *AudioSample) (*Intent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetectAudioIntent not implemented")
}
func (UnimplementedDialogServer) mustEmbedUnimplementedDialogServer() {}

// UnsafeDialogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DialogServer will
// result in compilation errors.
type UnsafeDialogServer interface {
	mustEmbedUnimplementedDialogServer()
}

func RegisterDialogServer(s grpc.ServiceRegistrar, srv DialogServer) {
	s.RegisterService(&_Dialog_serviceDesc, srv)
}

func _Dialog_DetectTextIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Detect)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DialogServer).DetectTextIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dialog/DetectTextIntent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DialogServer).DetectTextIntent(ctx, req.(*Detect))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dialog_DetectAudioIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AudioSample)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DialogServer).DetectAudioIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dialog/DetectAudioIntent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DialogServer).DetectAudioIntent(ctx, req.(*AudioSample))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dialog_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Dialog",
	HandlerType: (*DialogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DetectTextIntent",
			Handler:    _Dialog_DetectTextIntent_Handler,
		},
		{
			MethodName: "DetectAudioIntent",
			Handler:    _Dialog_DetectAudioIntent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dialog.proto",
}
